### ISSUE TITLE
Asking about the back-projected point cloud on S3DIS dataset

### ISSUE THREAD

**Issue by ngoductuanlhp** [minnjung/EP2P-Loc#1]
Hi @minnjung 
Thank you for your amazing paper and the code. However, when I tried to backproject the depth images into 3D space, I noticed that the generated point cloud didn't align with the ground-truth 3D point cloud. Here's what the result looks like:
<img width="666" alt="image" src="https://github.com/minnjung/EP2P-Loc/assets/39947254/45d9214e-2906-4dab-b149-a4d7f4f177e5">
The red points represent the projected points from the depth images, and the grey ones are from the ground-truth 3D point cloud. It appears that the locations are correct, but there's an issue with the local orientation. Do you have any insights or suggestions to address this problem?
Thank you.

**Comment by 1207koo** [comment]
Hello,
Thank you for your interest in our research!
We also encountered the same issue when initially projecting the point cloud from S3DIS.
Although it's not well-documented in the official repo of S3DIS(and 2D-3D-S), the problem arises because the point cloud is rotated from the conventional coordinate system we typically use.
If you have used the same projection method as us (camera coordinates with x, y, z being right, down, and front), then you should flip the y and z coordinates.
see: https://github.com/minnjung/EP2P-Loc/blob/main/datasets/preprocess/dataset_classes.py#L254
If you encounter similar issues in the future, please let us know. Thank you!
